### ISSUE TITLE
Script not showing flag and printing on past prompts

### ISSUE THREAD

**Issue by auroraanna** [trakBan/ipfetch#17]
![image](https://user-images.githubusercontent.com/81317317/159789644-be33ed53-86a8-44a1-a52a-0ad562c6a178.png)

I installed with the `setup.sh`
There is no flag as advertised. Also it prints on the prompts I already made. Didn't even know that's possible,

**Comment by Costinteo** [comment]
Are you sure you installed properly? You have to install using sudo. Is there anything in /usr/share?

I've tried reproducing it by reinstalling and using the IP in your screenshot, but it works properly for me.

**Comment by trakBan** [comment]
Did you install it properly, and how did you install it? From your output it seems like it couldnt find a flag in /usr/share/ipfetch. 
Can you run ```cat /usr/share/ipfetch/*``` and post your output?

**Comment by auroraanna** [comment]
`cat /usr/share/ipfetch/flags/*` prints all the flags.

**Comment by auroraanna** [comment]
Can't do `cat /usr/share/ipfetch/*` because there is only a directory in there no files.

**Comment by auroraanna** [comment]
> Did you install it properly, and how did you install it?

WIth the `setup.sh`

**Comment by Costinteo** [comment]
Ah, I think I might know where the problem lies. I'll take a look at it soon. The setup.sh also copies the flags directory and the script disregards the existence of that directory.

Solution would be to make the setup ignore the flags directory and only copy the ascii files, or make the script look one level deeper.

Honestly, just changing flags copying from the setup.sh to ``cp ./flags/* /usr/share/ipfetch/`` should be enough.

Can you also provide the output for ``cp --version``? I'm curious if you're somehow using something different. And also maybe the distro, if you're willing to share.

**Comment by trakBan** [comment]
Thats really weird behaviour, can you please share what distro you use and the output of ```cp --version```, so i can see what i can add in setup.sh to fix it for others that may encounter this issue in future.

**Comment by auroraanna** [comment]
> Can you also provide the output for cp --version? I'm curious if you're somehow using something different. And also maybe the distro, if you're willing to share.


```
~ ➜ cp --version
cp (GNU coreutils) 9.0
Packaged by https://NixOS.org
```
Yeah so I'm on NixOS. That is a problem sometimes but I don't see the problem here. Also got wget installed.

**Comment by Costinteo** [comment]
So I've investigated a bit. It seems like recursive copy behaves differently depending if the target directory exists, or not. Which makes sens, because you wouldn't want to overwrite a whole directory with the contents of the source, you'd want the source to be a directory inside the existing target directory.

I'm not sure that is the issue you're facing. Could you try uninstalling and installing again?

If this is not the problem, then maybe cp had something changed in the latest version. I'm using ``cp (GNU coreutils) 8.32``. I've tried checking out their changelog, but nothing seems weird. Only seemingly relevant thing is:
https://github.com/coreutils/coreutils/commit/7b5f0fa47cd04c84975250d5b5da7c98e097e99f

I'm not sure if it's truly the issue here, though. I'm not very familiar with the internal works of GNU coreutils. In the meantime, I will push a fix for it, to avoid recursion.

**Comment by auroraanna** [comment]
Uninstalling and then installing fixes the problem. But also I had to make sure that `/usr/share` exists (it doesn't by default on NixOS). Also even though the install somehow went wrong it still printed `ipfetch has been sucesfully installed.`. If [Nix](https://nixos.org) was used to install this all wouldn't have been a problem. You'd have no way of messing up the installation.

**Comment by Costinteo** [comment]
Thanks for the explanation! I didn't know ``/usr/share`` doesn't exist in NixOS. I thought it might be something like that. The pull request I sent should fix it regardless, because it creates the ``/usr/share`` path if it doesn't exist.
