### ISSUE TITLE
Continent field empty

### ISSUE THREAD

**Issue by auroraanna** [trakBan/ipfetch#19]
I tried my own ip adress and the ip adresses in the readme gif but the continent field is always empty.

**Comment by Costinteo** [comment]
This is most likely due to this sed, that removes underscores:
https://github.com/trakBan/ipfetch/blob/fc295bfda4f9fea6eee9f6f3f2dabc26b6f25be4/ipfetch#L53-L58

The regex for "continent_code" will probably fail because the underscore is removed. This happened in the latest commit: https://github.com/trakBan/ipfetch/commit/d76cfea361b39ef644edddcafaf02d4fa8c5bcd6
